### PR TITLE
Update integration test to 2.1.0

### PR DESCRIPTION
**Pull request by lumberj**

### CODE REVIEW

**Comment by clark800** [comment]
Is it intentional to pin the version?

**Comment by lumberj** [comment]
I thought that might help because the integration tests work fine on the connector:

Before thischange on notary
```
Projects/five-bells-notary [ilp_server_alpha] » grep integration package.json
    "five-bells-integration-test": "^2.0.0",
Projects/five-bells-notary [ilp_server_alpha] »
```

vs. current connector alpha branch

```
Projects/five-bells-connector [ilp_server_alpha] » grep integration package.json
    "five-bells-integration-test": "2.1.0",
```

**Comment by lumberj** [comment]
I'll try rebuilding without cache

**Comment by emschwartz** [comment]
@lumberj you can also put `^2.1.0`

**Pull request closed without merging**
