### PR TITLE
Notary now takes environment variables to set username and password it connects to Oracle database with.

### PR DESCRIPTION
**Pull request by naoitoi**

### CODE REVIEW

**Comment by lumberj** [comment]
I think this should be part of the local config, https://github.com/interledger/five-bells-notary/blob/master/src/lib/config.js

For examples, see: https://github.com/interledger/five-bells-ledger/blob/master/src/lib/config.js
and: https://github.com/interledger/five-bells-connector/blob/master/src/lib/config.js

**Comment by gip** [comment]
I think I agree with Alan - all config options should be extracted in the local config so that things can be mocked. Direct access to process.env should not happen beyond to the config module I'd think.

**Comment by naoitoi** [comment]
Thank you, @lumberj, @gip,
We had a discussion in January, and made a conscious decision to adopt 12 factor way - use environment variable for run time configuration. 
http://12factor.net/config
That's why we store DB configuration (how to connect to DB) in a configuration file, but which DB user Notary uses in this particular execution can be in environment variable. 

I'd welcome a discussion about "ilp-server should configure components in config files, rather than environment variables, because A and B".  But it'll be a big refactoring job (affects all components and all current environment variables), so I suggest we'll do it in another task.

**Comment by lumberj** [comment]
@naoitoi I think you misunderstood. The `config` module gets configuration from the environment. Most of the work is done already in [five-bells-shared](https://github.com/interledger/five-bells-shared/blob/master/lib/config.js). It would make sense to keep configuration of the app in a single place, as it's done elsewhere.

**Comment by gip** [comment]
LGTM

**Pull request merged**
