### PR TITLE
[CI] Parallelize Notary tests and use ci-npm-publish task from

### PR DESCRIPTION
**Pull request by lumberj**
five-bells-shared

Using
https://github.com/interledger/five-bells-shared/blob/master/bin/ci-publish.sh
to safely publish npm modules

Also adds testing on mysql and postgres. Publishing apidoc and coveralls.

Blocked by:
- Requires docker container to be registered
- Env variables for docker set in CircleCI

### CODE REVIEW

**Comment by lumberj** [comment]
cc @gip 

cc @justmoon this will require the container to be registered as you mentioned

**Comment by lumberj** [comment]
Don't merge until @justmoon adds the necessary env variables

screen shot 2016-03-29 at 6 42 35 pm

https://circleci.com/gh/interledger/five-bells-notary/edit#env-vars

**Comment by lumberj** [comment]
cc @naoitoi

**Comment by lumberj** [comment]
Should be ready to merge. Need to look at the CI test results for container 3, where Oracle tests run.

**Comment by clark800** [comment]
LGTM

**Pull request merged**
